services:
  backend:
    image: ${BACKEND_IMAGE_REPOSITORY}:${BACKEND_IMAGE_TAG}
    container_name: community-backend
    restart: unless-stopped
    ports:
      - "80:8080"

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      ACCESS_TOKEN_EXP: ${ACCESS_TOKEN_EXP}
      REFRESH_TOKEN_EXP: ${REFRESH_TOKEN_EXP}

      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_PUBLIC_BASE_URL: ${AWS_S3_PUBLIC_BASE_URL}
      CLOUD_AWS_S3_PUBLIC_BASE_URL: ${AWS_S3_PUBLIC_BASE_URL}

      # Tomcat Thread Pool
      TOMCAT_MAX_THREADS: ${TOMCAT_MAX_THREADS}
      TOMCAT_MIN_SPARE_THREADS: ${TOMCAT_MIN_SPARE_THREADS}

      # HikariCP
      HIKARI_MAX_POOL_SIZE: ${HIKARI_MAX_POOL_SIZE}
      HIKARI_MIN_IDLE: ${HIKARI_MIN_IDLE}

    volumes:
      - backend_images:/app/image

    networks:
      - backend

volumes:
  backend_images:

networks:
  backend:
    driver: bridge
