spring:
  application:
    name: backend

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
