apiVersion: v1
kind: ConfigMap
metadata:
  name: community-backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "community-backend.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.SPRING_PROFILES_ACTIVE | quote }}
  TOMCAT_MAX_THREADS: {{ .Values.config.TOMCAT_MAX_THREADS | quote }}
  TOMCAT_MIN_SPARE_THREADS: {{ .Values.config.TOMCAT_MIN_SPARE_THREADS | quote }}
  HIKARI_MAX_POOL_SIZE: {{ .Values.config.HIKARI_MAX_POOL_SIZE | quote }}
  HIKARI_MIN_IDLE: {{ .Values.config.HIKARI_MIN_IDLE | quote }}
  AWS_REGION: {{ .Values.config.AWS_REGION | quote }}
