{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "community-backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "community-backend.labels" . | nindent 4 }}
    release: {{ .Values.serviceMonitor.releaseLabel | quote }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "community-backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}